In [1]:
arr=[8, 7, 2, 5, 3, 1]
_sum=10
for i in range(len(arr)):
    for j in range(i+1,len(arr)):
        if arr[i]+arr[j]==_sum:
            print(i,j)

0 2
1 4


In [2]:
arr=[8, 7, 2, 5, 3, 1]
_sum=10
_dict={}
for i in range(len(arr)):
    if (_sum-arr[i]) in _dict:
        print(_dict[_sum-arr[i]],i)
    _dict[arr[i]]=i

0 2
1 4


In [3]:
from copy import copy
arr=[8, 7, 2, 5, 3, 1]
_sum=10
srt_arr=copy(arr)
srt_arr.sort()
low=0;high=len(arr)-1
while low < high:
    if (srt_arr[low]+srt_arr[high])==_sum:
        print(arr.index(srt_arr[low]),arr.index(srt_arr[high]))
        low+=1
    elif (srt_arr[low]+srt_arr[high])<_sum:
        low+=1
    else:
        high-=1

2 0
4 1


In [4]:
arr=[ -2,-3,5,4, 2, -3, -1, 0, 4 ]
_sum=0
_dict={0:0}
_total=0
for i in range(len(arr)):
    _total+=arr[i]
    #print('..',i,_total)
    if _total in _dict:
        print(_dict[_total],i+1)
        print(arr[_dict[_total]:i+1])
    else:
        _dict[_total]=i+1

0 3
[-2, -3, 5]
7 8
[0]
5 9
[-3, -1, 0, 4]


In [5]:
arr=[1,2,3,4,5,2,3,5,7,8,9 ]
_sum=10
_dict={0:0}
_total=0
for i in range(len(arr)):
    _total+=arr[i]
    #print(_total)
    if (_total-_sum) in _dict:
        print(_dict[_total-_sum],i+1)
        print(arr[_dict[_total-_sum]:i+1])
    else:
        _dict[_total]=i+1

0 4
[1, 2, 3, 4]
5 8
[2, 3, 5]


In [6]:
_stra='ababaa'
_strb='aa'
def get_possible_sufixes(_str):
    _res=[]
    for i in range(len(_str)):
        _res+=[_str[i:]]
    return _res

def calc_similarity_sum(_stra):
    _sufixes=get_possible_sufixes(_stra)
    _total_score=0
    for _sufix in _sufixes:
        _score=0
        for ch_a,ch_b in zip(_stra,_sufix):
            #print(ch_a,ch_b)
            if ch_a !=ch_b: break
            else: _score+=1
        _total_score+=_score
    print(_total_score)
calc_similarity_sum(_stra)
calc_similarity_sum(_strb)

11
3


In [7]:
a=set([1])
a.remove(1)
a

set()

In [8]:
def get_possible_sufixes(_str):
    _res=set()
    for i in range(len(_str)):
        _res.add(_str[i:])
    return _res


def stringSimilarity(s):
    _sufixes=get_possible_sufixes(s)
    _total_score=0
    for i in range(len(s)):
        if s[:i] in _sufixes: 
            _total_score+=i
            _sufixes.remove(s[:i])
        
    for _sufix in _sufixes:
        _score=0
        for ch_a,ch_b in zip(s,_sufix):
            #print(ch_a,ch_b)
            if ch_a !=ch_b: break
            else: _score+=1
        _total_score+=_score
    return _total_score

stringSimilarity(_stra)

11

In [9]:
import numpy as np

In [10]:
nx,ny=4,4
crds=[]
for i in range(1,nx):
    for j in range(1,ny):
        crds+=[[i,j]]
crds

[[1, 1], [1, 2], [1, 3], [2, 1], [2, 2], [2, 3], [3, 1], [3, 2], [3, 3]]

In [11]:
#if (x+1,y) in crds  and (x,y+1) in crds and (x+1,y+1) in crds:
def expand_x_dirr(x1,y1,x2,y2,count=0):
    if [x1+1,y1] in crds and [x2+1,y2] in crds:
        count+=1
        #print(x1+1,x2+1)
        count=expand_x_dirr(x1+1,y1,x2+1,y2,count)
    else:
        return count
    return count
ret=0
for y1 in range(1,ny-1):
    for y2 in range(y1,ny):
        x1=1;x2=1
        ret+=expand_x_dirr(1,y1,1,y2)  
        print(ret)

2
4
6
8
10


In [12]:
ret=0
for x1 in range(1,nx-1):
    for x2 in range(x1+1,nx):
        for y1 in range(1,ny-1):
            for y2 in range(y1+1,ny):
                if [x1,y1] in crds and [x1+1,y1] in crds and [x1,y1+1] in crds and [x2,y2] in crds:
                    #if abs(x2-x1) and abs(y2-y1):
                    print([x1,y1],[x2,y2])
                    ret+=1
print(ret)

[1, 1] [2, 2]
[1, 1] [2, 3]
[1, 2] [2, 3]
[1, 1] [3, 2]
[1, 1] [3, 3]
[1, 2] [3, 3]
[2, 1] [3, 2]
[2, 1] [3, 3]
[2, 2] [3, 3]
9


In [13]:
if [2,2] in crds and [2,2] in crds:
    print('True')

True


In [14]:
from itertools import combinations as icomb
from itertools import permutations as iperm
n=3
_input=['a','b','c','d']
ret=iperm(_input,n)
list(ret)

[('a', 'b', 'c'),
 ('a', 'b', 'd'),
 ('a', 'c', 'b'),
 ('a', 'c', 'd'),
 ('a', 'd', 'b'),
 ('a', 'd', 'c'),
 ('b', 'a', 'c'),
 ('b', 'a', 'd'),
 ('b', 'c', 'a'),
 ('b', 'c', 'd'),
 ('b', 'd', 'a'),
 ('b', 'd', 'c'),
 ('c', 'a', 'b'),
 ('c', 'a', 'd'),
 ('c', 'b', 'a'),
 ('c', 'b', 'd'),
 ('c', 'd', 'a'),
 ('c', 'd', 'b'),
 ('d', 'a', 'b'),
 ('d', 'a', 'c'),
 ('d', 'b', 'a'),
 ('d', 'b', 'c'),
 ('d', 'c', 'a'),
 ('d', 'c', 'b')]

In [29]:
lst=['a','b','c','d']
def comb_v1(lst):
    if len(lst)==0: return [[]]
    _seqs=[]
    _first=[lst[0]]
    _exc_first=lst[1:]
    _exc_first_combs=comb_v1(_exc_first)
    
    for _comb in _exc_first_combs:
        _seqs.append(_first+_comb)
    return _seqs+_exc_first_combs
#comb_all(lst)

def comb_all(lst):
    if len(lst)==0: return [[]]
    _seqs=[]
    for i in range(len(lst)):
        _first=[lst[i]]
        _exc_first=lst[:i]+lst[i+1:]
        _exc_first_combs=comb_all(_exc_first)

        for _comb in _exc_first_combs:
            _seqs.append(_first+_comb)
    return _seqs+_exc_first_combs

def perm_all(lst):
    if len(lst)==0: return [[]]
    _seqs=[]
    for i in range(len(lst)):
        _first=[lst[i]]
        _exc_first=lst[:i]+lst[i+1:]
        _exc_first_combs=perm_all(_exc_first)

        for _comb in _exc_first_combs:
            _seqs.append(_first+_comb)
    return _seqs+_exc_first_combs

perm_all(lst)

[['a', 'b', 'c', 'd'],
 ['a', 'b', 'c'],
 ['a', 'b', 'd', 'c'],
 ['a', 'b', 'd'],
 ['a', 'b', 'c'],
 ['a', 'b'],
 ['a', 'c', 'b', 'd'],
 ['a', 'c', 'b'],
 ['a', 'c', 'd', 'b'],
 ['a', 'c', 'd'],
 ['a', 'c', 'b'],
 ['a', 'c'],
 ['a', 'd', 'b', 'c'],
 ['a', 'd', 'b'],
 ['a', 'd', 'c', 'b'],
 ['a', 'd', 'c'],
 ['a', 'd', 'b'],
 ['a', 'd'],
 ['a', 'b', 'c'],
 ['a', 'b'],
 ['a', 'c', 'b'],
 ['a', 'c'],
 ['a', 'b'],
 ['a'],
 ['b', 'a', 'c', 'd'],
 ['b', 'a', 'c'],
 ['b', 'a', 'd', 'c'],
 ['b', 'a', 'd'],
 ['b', 'a', 'c'],
 ['b', 'a'],
 ['b', 'c', 'a', 'd'],
 ['b', 'c', 'a'],
 ['b', 'c', 'd', 'a'],
 ['b', 'c', 'd'],
 ['b', 'c', 'a'],
 ['b', 'c'],
 ['b', 'd', 'a', 'c'],
 ['b', 'd', 'a'],
 ['b', 'd', 'c', 'a'],
 ['b', 'd', 'c'],
 ['b', 'd', 'a'],
 ['b', 'd'],
 ['b', 'a', 'c'],
 ['b', 'a'],
 ['b', 'c', 'a'],
 ['b', 'c'],
 ['b', 'a'],
 ['b'],
 ['c', 'a', 'b', 'd'],
 ['c', 'a', 'b'],
 ['c', 'a', 'd', 'b'],
 ['c', 'a', 'd'],
 ['c', 'a', 'b'],
 ['c', 'a'],
 ['c', 'b', 'a', 'd'],
 ['c', 'b', 'a'],
 [

In [33]:
_input=['a','b','c','d']
def comb(_inp):
    if len(_inp)==0:return [[]]
    _seqs=[]
    _first=[_inp[0]]
    _exc_first=_inp[1:]
    _exc_first_combs=comb(_exc_first)
    for _comb in _exc_first_combs:
        _seqs.append(_first+_comb)
    return _seqs+_exc_first_combs
comb(_input)

[['a', 'b', 'c', 'd'],
 ['a', 'b', 'c'],
 ['a', 'b', 'd'],
 ['a', 'b'],
 ['a', 'c', 'd'],
 ['a', 'c'],
 ['a', 'd'],
 ['a'],
 ['b', 'c', 'd'],
 ['b', 'c'],
 ['b', 'd'],
 ['b'],
 ['c', 'd'],
 ['c'],
 ['d'],
 []]

In [9]:
_input=['a','b','c','d']
def comb(_inp,n):
    if n==0:return [[]]
    _seqs=[]
    for i in range(0,len(_inp)):
        _first=[_inp[i]]
        _exc_first=_inp[i+1:]
        _exc_first_combs=comb(_exc_first,n-1)
        for _comb in _exc_first_combs:
            _seqs.append(_first+_comb)
    return _seqs

def perm(_inp,n):
    if n==0:return [[]]
    _seqs=[]
    for i in range(0,len(_inp)):
        _first=[_inp[i]]
        _exc_first=_inp[:i]+_inp[i+1:]
        _exc_first_combs=perm(_exc_first,n-1)
        for _comb in _exc_first_combs:
            _seqs.append(_first+_comb)
    return _seqs

print('Combinations')
print(comb(_input,3))
print('Permutations')
print(perm(_input,3))

Combinations
[['a', 'b', 'c'], ['a', 'b', 'd'], ['a', 'c', 'd'], ['b', 'c', 'd']]
Permutations
[['a', 'b', 'c'], ['a', 'b', 'd'], ['a', 'c', 'b'], ['a', 'c', 'd'], ['a', 'd', 'b'], ['a', 'd', 'c'], ['b', 'a', 'c'], ['b', 'a', 'd'], ['b', 'c', 'a'], ['b', 'c', 'd'], ['b', 'd', 'a'], ['b', 'd', 'c'], ['c', 'a', 'b'], ['c', 'a', 'd'], ['c', 'b', 'a'], ['c', 'b', 'd'], ['c', 'd', 'a'], ['c', 'd', 'b'], ['d', 'a', 'b'], ['d', 'a', 'c'], ['d', 'b', 'a'], ['d', 'b', 'c'], ['d', 'c', 'a'], ['d', 'c', 'b']]


In [2]:
arr=[1,2,3,4,5]
def rec_sum(arr):
    if len(arr)==0: return 0
    _sum=arr[0]+rec_sum(arr[1:])
    return _sum
rec_sum(arr)

15

In [ ]:
O(n)
O(log(n))
O(nlog(n))
O(n^p) -> O(n^2)
O(b^n) -> O(2^n)
O(n!)

### Knap Scak

In [2]:
prob=2
def get_prob(prob=1):
    if prob==1:
        val = [60, 100, 120,100]
        wts = [10, 20, 30,20]
        W = 50

    if prob==2:
        val = [60, 100, 120,200]
        wts = [10, 20, 30,30]
        W = 60

    if prob==3:
        val = [50,100,150,200]
        wts = [8,16,32,40]
        W = 64
        
    if prob==4:
        val = [5,10,15,20]
        wts = [2,4,8,10]
        W = 20
    return val,wts,W

In [3]:
val,wts,W=get_prob(prob=1)

In [4]:
_input=['a','b','c','d']
def comb(_inp):
    if len(_inp)==0:return [[]]
    _seqs=[]
    _first=[_inp[0]]
    _exc_first=_inp[1:]
    _exc_first_combs=comb(_exc_first)
    for _comb in _exc_first_combs:
        _seqs.append(_first+_comb)
    return _seqs+_exc_first_combs
comb(val)

[[60, 100, 120, 100],
 [60, 100, 120],
 [60, 100, 100],
 [60, 100],
 [60, 120, 100],
 [60, 120],
 [60, 100],
 [60],
 [100, 120, 100],
 [100, 120],
 [100, 100],
 [100],
 [120, 100],
 [120],
 [100],
 []]

In [20]:
def knapsack_1(val,wts,n=-1,_v=0,_w=0):
    if n == len(val)-1 or _w>= W : return _v,_w
    n+=1
    _v1,_w1=knapsack_1(val,wts,n=n,_v=_v,_w=_w)
    if _w+wts[n]<=W:
       _v2,_w2=knapsack_1(val,wts,n=n,_v=_v+val[n],_w=_w+wts[n])
    else:
       _v2,_w2=_v,_w
    #print(_v1,_v2)
    if _v1>_v2 : return _v1,_w1
    else: return _v2,_w2
    
def knapsack_2(val,wts,n,_v=0,_w=0):
    if n == 0 or _w>=W: return _v,_w
    n-=1
    _v1,_w1=knapsack_2(val,wts,n,_v=_v,_w=_w)
    _v2,_w2=knapsack_2(val,wts,n,_v=_v+val[n],_w=_w+wts[n])
    
    #print(_v1,_v2)
    if _v1>_v2 : return _v1,_w1
    else: return _v2,_w2

print('knapsack_1 : ')
for i in [1,2,3]:
    val,wts,W=get_prob(prob=i)
    _v,_w=knapsack_1(val,wts)
    print(_v)
print('knapsack_2 : ')
for i in [1,2,3]:
    val,wts,W=get_prob(prob=i)
    _v,_w=knapsack_2(val,wts,len(val))
    print(_v)

knapsack_1 : 
260
360
350
knapsack_2 : 
260
360
350


In [9]:
'''
val,wts,W=get_prob(prob=1)
def knapSack_1(W, wt, val, n):
  
    # Base Case
    if n == 0 or W == 0 :
        return 0
  
    # If weight of the nth item is more than Knapsack of capacity
    # W, then this item cannot be included in the optimal solution
    if (wt[n-1] > W):
        #print(wt[n-1],W)
        return knapSack_1(W, wt, val, n-1)
  
    # return the maximum of two cases:
    # (1) nth item included
    # (2) not included
    else:
        return max(val[n-1] + knapSack_1(W-wt[n-1], wt, val, n-1),
                   knapSack_1(W, wt, val, n-1))
ret=knapSack_1(W,wts, val, len(val))
print(ret)
'''

def knapsack(wts, val, n,_w=W,_v=0):
  
    # Base Case
    if n == 0:
        return 0,0
  
    # If weight of the nth item is more than Knapsack of capacity
    # W, then this item cannot be included in the optimal solution
    #print(n)
    if (wts[n-1] > _w):
        return knapsack( wts, val, n-1,_w=_w,_v=_v)
        #pass
    # return the maximum of two cases:
    # (1) nth item included
    # (2) not included
    else:
        _v1,_w1=knapsack(wts, val, n-1,_w=_w-wts[n-1],_v=_v)
        _v1=_v1+val[n-1]
        _v2,_w2=knapsack(wts, val, n-1,_w=_w,_v=_v)
        if _v1>_v2: return _v1,_w1
        else: return _v2,_w2
        
for i in [1,2,3]:
    val,wts,W=get_prob(prob=i)
    _v,_w=knapsack(wts,val,len(val),_w=W,_v=0)
    print(_v)

260
360
350


In [12]:
def knapSack(W, wt, val): 
    n=len(val)
    table = [[0 for x in range(W + 1)] for x in range(n + 1)] 
    print(np.array(table))
    for i in range(n + 1): 
        for j in range(W + 1): 
            if i == 0 or j == 0: 
                table[i][j] = 0
            elif wt[i-1] <= j: 
                table[i][j] = max(val[i-1]  + table[i-1][j-wt[i-1]],  table[i-1][j]) 
            else: 
                table[i][j] = table[i-1][j] 
    print(np.array(table))
    return table[n][W] 
 
#print(knapSack(W, wts, val))
for i in [4]:
    val,wts,W=get_prob(prob=i)
    print('',val,'\n',wts,W)
    _v=knapSack(W,wts,val)
    print(_v)

 [5, 10, 15, 20] 
 [2, 4, 8, 10] 20
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5]
 [ 0  0  5  5 10 10 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15]
 [ 0  0  5  5 10 10 15 15 15 15 20 20 25 25 30 30 30 30 30 30 30]
 [ 0  0  5  5 10 10 15 15 15 15 20 20 25 25 30 30 35 35 35 35 40]]
40


### Least Common Subsequence

In [31]:
seq=[]
def LCS(i,j):
    if i>= len(str1) or j>= len(str2):
        return 0
    
    if str1[i]==str2[j]:
        seq.append(str1[i])
        return 1+ LCS(i+1,j+1)
    
    else:
        return max(LCS(i+1,j),LCS(i,j+1))
str1='longest'
str2='stone'
str1='abcde'
str2='ade'
LCS(0,0)

3

In [32]:
#def LCS():
seq=[];res=0
table = [[0 for _ in range(len(str2)+1)] for _ in range(len(str1)+1)]
for i in range(len(str1)+1):
    for j in range(len(str2)+1):
        if i==0 or j==0:
            pass
        elif str1[i-1]==str2[j-1]:
            seq.append(str1[i-1])
            table[i][j]=1+table[i-1][j-1]
            res=max(res,table[i][j])
        else:
            table[i][j]=max(table[i-1][j],table[i][j-1])
table,res

([[0, 0, 0, 0],
  [0, 1, 1, 1],
  [0, 1, 1, 1],
  [0, 1, 1, 1],
  [0, 1, 2, 2],
  [0, 1, 2, 3]],
 3)

### Least common substring

In [94]:
import numpy as np
str1='abcdefgh'
str2='bcdgh'
#def LCS():
seq=[]
table = [[0 for _ in range(len(str2)+1)] for _ in range(len(str1)+1)]
_len=0
for i in range(len(str1)+1):
    for j in range(len(str2)+1):
        if i==0 or j==0:
            pass
        elif str1[i-1]==str2[j-1]:
            seq.append(str1[i-1])
            table[i][j]=1+table[i-1][j-1]
            if table[i][j]>_len:
                _len=table[i][j]
                row=i
                col=j
        else:
            table[i][j]=0#max(table[i-1][j],table[i][j-1])

print(np.array(table),_len)
out_str=['0']*_len
while(table[row][col]):
    _len-=1
    row-=1
    col-=1
    out_str[_len]=str1[row]
out_str

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 2]] 3


['b', 'c', 'd']

In [100]:
def LIS(arr):
    lis=[1]*len(arr)
    seq=[]
    for i in range(1,len(arr)):
        for j in range(i):
            #if arr[i]>arr[j]:
            #    lis[i]=max(lis[i],lis[j]+1)
            if arr[i]>arr[j] and lis[j]+1 > lis[i]:
                lis[i]=lis[j]+1
        seq.append(arr[i])
    print(seq,lis)
    return max(lis)

arr = [10, 22, 9, 33, 21, 50, 41, 60]
LIS(arr)

[10, 22, 9, 33, 21, 50, 41, 60] [1, 1, 2, 1, 3, 2, 4, 4, 5]


5

In [83]:
[1, 2, 1, 3, 2, 4, 4, 5]

['b', 'c', 'd']

In [176]:
import numpy as np
from collections import deque
rows=6
cols=6
Q=rows
grid=np.zeros((rows,cols))

In [177]:
def is_valid(i,j,_grid):
    #if i>=rows: return False
    #if j>=cols: return False
    
    if any(_grid[:,j]): return False
    if any(_grid[i,:]): return False
    _i=i;_j=j
    while _i >=0 and _j>=0:
        if _grid[_i,_j]==1: return False
        _i-=1;_j-=1
        
    _i=i;_j=j
    while _i >=0 and _j<cols:
        if _grid[_i,_j]==1: return False
        _i-=1;_j+=1
    
    '''
    _i=i;_j=j
    while _i<rows and _j<cols:
        if _grid[_i,_j]==1: return False
        _i+=1;_j+=1
        
    _i=i;_j=j
    while _i <rows and _j>=0:
        if _grid[_i,_j]==1: return False
        _i+=1;_j-=1
    '''
    return True

def n_queen(grid):
    grid_cp=grid.copy()
    k=0
    q_count=Q;row_st=0;col_st=0;last_col=0
    col_q=deque();_row=0;_col=0
    while(q_count):
        for row in range(_row,rows):
            for col in range(_col,cols):
                if is_valid(row,col,grid_cp):
                    grid_cp[row,col]=1
                    col_q.append([row,col]) 
                    break
                    
            print(grid_cp)

            if not any(grid_cp[row,:]):
                _row,_col=col_q.pop()
                grid_cp[_row,_col]=0
                _col+=1                
                print('..............',_col)
                break    
            else:
                _col=0
                
        if k==100: break
        k+=1
        #break

In [178]:
n_queen(grid)

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
.............. 4
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
.............. 2
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 

In [42]:
grid[0,0]=0
list(grid[0,:]).index(1)

ValueError: 1 is not in list

In [169]:
for i in range(4):
    print(i)
    continue

0
1
2
3
